### ISSUE TITLE
beepvar

### ISSUE THREAD

**Issue by khoore** [jmbh/mlVARGD#1] opened 2024-06-14 08:42 UTC
Thanks for creating this the interesting package! Just to let you know that, although specification of 'beepvar' is mentioned as optional, when not including this in mlVAR_GC() it will cause an error stating that "task 1 failed - "'beepvar' must be a string indicating a column name of the data.'", resulting in no objects being stored.

**Comment by jmbh** [comment] 2024-06-14 11:58
Hi khoore, 

Thanks for reporting this!

Any chance you could give me a reproducible example for this error? 

I just ran the package example in ?mlVAR_GC, in which the argument "beepvar" is missing and the function runs through fine, so I cannot reproduce this.

Thanks,
Jonas

**Comment by khoore** [comment] 2024-06-14 12:12
Hi Jonas

Thanks for the fast reply! I've had the error with my own data, but just reproduced it using the internal data of the package, also used in the tutorial paper:
R-code:
library(mnet)
dim(dataKoval13)
length(unique(unique(dataKoval13$PID)))
output <- mlVAR_GC(data = dataKoval13,
                   vars = colnames(dataKoval13)[6:12],
                   idvar = "PID",
                   dayvar = "UNIT",
                   groups = "group",
                   test = "permutation",
                   nP = 10,
                   nCores = 12,
                   pbar = TRUE)

Print-screen of error:
***@***.***

Fyi, for version info:
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=Dutch_Belgium.utf8  LC_CTYPE=Dutch_Belgium.utf8    LC_MONETARY=Dutch_Belgium.utf8 LC_NUMERIC=C
[5] LC_TIME=Dutch_Belgium.utf8

time zone: Europe/Brussels
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] mnet_0.1.2      esmpack_0.1-17  remotes_2.4.2.1 dplyr_1.1.2

loaded via a namespace (and not attached):
  [1] RColorBrewer_1.1-3          rstudioapi_0.14             shape_1.4.6                 magrittr_2.0.3              jomo_2.7-6
  [6] nloptr_2.0.3                rmarkdown_2.23              vctrs_0.6.3                 minqa_1.2.5                 heplots_1.4-2
 [11] mlVAR_0.5.1                 base64enc_0.1-3             htmltools_0.5.5             polynom_1.4-1               plotrix_3.8-2
 [16] curl_5.0.2                  weights_1.0.4               broom_1.0.5                 Formula_1.2-5               mitml_0.4-5
 [21] TTR_0.24.3                  htmlwidgets_1.6.2           gsubfn_0.7                  plyr_1.8.8                  zoo_1.8-12
 [26] igraph_1.5.0                lifecycle_1.0.3             iterators_1.0.14            pkgconfig_2.0.3             Matrix_1.5-4.1
 [31] R6_2.5.1                    fastmap_1.1.1               digest_0.6.32               fdrtool_1.2.17              colorspace_2.1-0
 [36] Hmisc_5.1-0                 ellipse_0.4.5               clusterGeneration_1.3.8     fansi_1.0.4                 nnls_1.4
 [41] gdata_2.19.0                httr_1.4.7                  abind_1.4-5                 compiler_4.3.1              proxy_0.4-27
 [46] pander_0.6.5                NetworkComparisonTest_2.2.2 doParallel_1.0.17           glasso_1.11                 htmlTable_2.4.1
 [51] backports_1.4.1             tseries_0.10-54             carData_3.0-5               psych_2.3.6                 fastDummies_1.7.3
 [56] R.utils_2.12.2              pan_1.8                     MASS_7.3-60                 corpcor_1.6.10              gtools_3.9.4
 [61] tools_4.3.1                 pbivnorm_0.6.0              MplusAutomation_1.1.0       foreign_0.8-84              quantmod_0.4.25
 [66] nnet_7.3-19                 R.oo_1.25.0                 glue_1.6.2                  quadprog_1.5-8              nlme_3.1-162
 [71] graphicalVAR_0.3.3          grid_4.3.1                  checkmate_2.2.0             cluster_2.1.4               reshape2_1.4.4
 [76] generics_0.1.3              gtable_0.3.3                R.methodsS3_1.8.2           class_7.3-22                tidyr_1.3.0
 [81] data.table_1.14.8           car_3.1-2                   utf8_1.2.3                  foreach_1.5.2               pillar_1.9.0
 [86] stringr_1.5.0               splines_4.3.1               smacof_2.1-5                networktools_1.5.0          lattice_0.21-8
 [91] survival_3.5-5              tidyselect_1.2.0            pbapply_1.7-2               knitr_1.43                  gridExtra_2.3
 [96] IsingFit_0.3.1              stats4_4.3.1                xfun_0.39                   texreg_1.38.6               qgraph_1.9.5
[101] arm_1.13-1                  proto_1.0.0                 stringi_1.7.12              yaml_2.3.7                  boot_1.3-28.1
[106] evaluate_0.21               codetools_0.2-19            wordcloud_2.6               tibble_3.2.1                cli_3.6.1
[111] rpart_4.1.19                xtable_1.8-4                munsell_0.5.0               lavaan_0.6-15               candisc_0.8-6
[116] Rcpp_1.0.10                 coda_0.19-4                 png_0.1-8                   parallel_4.3.1              ggplot2_3.4.2
[121] jpeg_0.1-10                 lme4_1.1-33                 glmnet_4.1-7                mvtnorm_1.2-2               scales_1.2.1
[126] xts_0.13.1                  e1071_1.7-13                eigenmodel_1.11             purrr_1.0.1                 rlang_1.1.1
[131] mnormt_2.1.1                mice_3.16.0

Hope this helps!

Best
Kristof

Van: jmbh ***@***.***>
Verzonden: vrijdag 14 juni 2024 13:59
Aan: jmbh/mlVARGD ***@***.***>
CC: Kristof Hoorelbeke ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jmbh/mlVARGD] beepvar (Issue #1)


Hi khoore,

Thanks for reporting this!

Any chance you could give me a reproducible example for this error?

I just ran the package example in ?mlVAR_GC, in which the argument "beepvar" is missing and the function runs through fine, so I cannot reproduce this.

Thanks,
Jonas

-

**Comment by jmbh** [comment] 2024-06-14 13:01
Hi khoore,

Thanks!

Should be fixed now on the Github version:
devtools(mnet)
install_github("jmbh/mnet")

Best wishes,
Jonas

**Comment by khoore** [comment] 2024-06-14 14:02
Perfect, this works. Thanks!

Van: jmbh ***@***.***>
Verzonden: vrijdag 14 juni 2024 15:02
Aan: jmbh/mlVARGD ***@***.***>
CC: Kristof Hoorelbeke ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jmbh/mlVARGD] beepvar (Issue #1)


Hi khoore,

Thanks!

Should be fixed now on the Github version:
devtools(mnet)
install_github("jmbh/mnet")

Best wishes,
Jonas

-

**Comment by jmbh** [comment] 2024-06-14 14:54
OK, good to hear!

**Closed as completed by jmbh** 2024-06-14 14:54 UTC
